name: doctor_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  go_router: ^16.1.0
  dio: ^5.9.0
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.9.1
  equatable: ^2.0.7
  very_good_analysis: ^9.0.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pretty_dio_logger: ^1.4.0
flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
  # dart run icons_launcher:create
# flutter gen-l10n